<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>Resources\Picture\ColorPickerWPF.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Picture\ColorPickerWPF.ico" />
    <None Remove="Resources\Picture\ColorPickerWPF.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Picture\ColorPickerWPF.ico" />
    <EmbeddedResource Include="Resources\Picture\ColorPickerWPF.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
  </ItemGroup>

</Project>
